package command

var Commands = []Command{
	AboutCommand{},
	AddCommand{},
	AddAdminCommand{},
	AddSupportCommand{},
	AdminCommand{},
	BlacklistCommand{},
	CancelCommand{},
	TagCommand{},
	CloseCommand{},
	HelpCommand{},
	ManageTags{},
	OpenCommand{},
	PanelCommand{},
	PremiumCommand{},
	RemoveCommand{},
	RemoveAdminCommand{},
	RemoveSupportCommand{},
	RenameCommand{},
	SetupCommand{},
	StatsCommand{},
	SyncCommand{},
	ViewStaffCommand{},
	VoteCommand{},
}
