package command

var Commands = []Command{
	AboutCommand{},
	AddCommand{},
	AddAdminCommand{},
	AddSupportCommand{},
	AdminCommand{},
	BlacklistCommand{},
	CancelCommand{},
	CannedResponseCommand{},
	CloseCommand{},
	HelpCommand{},
	ManageCannedResponses{},
	OpenCommand{},
	PanelCommand{},
	PremiumCommand{},
	PurgeCommand{},
	RemoveCommand{},
	RemoveAdminCommand{},
	AdminResetCommand{},
	RemoveSupportCommand{},
	SetupCommand{},
	StatsCommand{},
	VoteCommand{},
}
